services:
  marketing-site:
    build: ./marketing-site
    container_name: 0xbuglabs-acme-marketing-site
    ports:
      - "8084:8084"
    restart: unless-stopped

  legacy-portal:
    build: ./legacy-portal
    container_name: 0xbuglabs-acme-legacy-portal
    ports:
      - "8085:8085"
    restart: unless-stopped
